### ISSUE TITLE
BiuBiuBiu~

### ISSUE THREAD

**Issue by hycinth22** [belanhd/learn-git#2]

**Comment by SpongeBobSun** [comment]
Well done bro!
![687474703a2f2f7777342e73696e61696d672e636e2f6c617267652f3565396138316462677731657539306d30387638366a323064773039613379752e6a7067](https://cloud.githubusercontent.com/assets/11534766/10987562/799a6d44-846f-11e5-8a4e-ac29d9081e5f.jpeg)

**Comment by axiaoxin** [comment]
Oh my baby, open source project is sacred. :angry:
